feat: fd/install UI updates
nuonco/installer pull request #42
Opened 2024-07-02 21:07 UTC by fidiego

### Description 

Applies a series of small UI changes and theme updates.

2024-07-02 21:52 UTC, jordan-acosta requested changes

2024-07-02 21:52 UTC, jordan-acosta commented on theme.ts
> +};
We don't want to check this file in.

So, this is a bit of an issue with our current development workflow for the installer. Ideally, we could .gitignore it, but in the forks we _do_ need to check the file in, so it's there to be loaded in the vercel deployment.

2024-07-02 21:52 UTC, jordan-acosta commented on theme.ts.example
> +        "step-active-border-color": colors.green["500"],
very nice

2024-07-02 21:52 UTC, jordan-acosta commented on components/Video.tsx
> +    <div className="relative pb-[56.25%] h-0 overflow-hidden max-w-full rounded-md">
We should add this border radius to the theme, alongside the card and button border radiuses.

2024-07-02 22:40 UTC, fidiego commented
@jordan-acosta this should be good to go

2024-07-08 17:39 UTC, fidiego commented
@jordan-acosta this PR has been rebased and works with the upstream changes. 

Note: i modified the method for selecting darkMode so i could debug by toggling the setting in my browser dev tools.

2024-07-08 19:06 UTC, jordan-acosta requested changes
The colors on the stepper UI appear to be mis-matched. The step circles are green or orange based on status, but the lines are still using the primary color.

<img width="1051" alt="Screenshot 2024-07-08 at 11 57 29 AM" src="https://github.com/nuonco/installer/assets/1048009/6a368da8-5fc4-47a1-9bd6-322c67e4eee3">


Also, so far, I don't think any of our vendors are using media queries for dark mode, and just use a single color scheme. Using media for dev makes sense, but we may want to leave in the selector setting most vendor will probably use.

```js
  darkMode: ["media", ["@media (prefers-color-scheme: dark)", "&:is(.dark *)"]],
  // Use this to statically set dark or light mode.
  // darkMode: "selector",
  forceDarkMode: false,
```

2024-07-08 19:18 UTC, merged